//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelShare {
    
    
    public partial class usuario_timeline {
        
        /// <summary>
        /// menuUsuarioLogado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TravelShare.includes.menu_usuario_logado menuUsuarioLogado;
        
        /// <summary>
        /// BoxPostagem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TravelShare.includes.BoxPostagem BoxPostagem;
        
        /// <summary>
        /// posts_usuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl posts_usuario;
        
        /// <summary>
        /// BarraAtividades control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TravelShare.includes.BarraAtividades BarraAtividades;
    }
}
