#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelShare.Modules
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="travelshare")]
	public partial class AcessaBanco : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public AcessaBanco() : 
				base(global::TravelShare.Properties.Settings.Default.BancoDeDados, mappingSource)
		{
			OnCreated();
		}
		
		public AcessaBanco(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcessaBanco(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcessaBanco(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcessaBanco(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USU_ID;
		
		private string _USU_NOME;
		
		private string _USU_SOBRENOME;
		
		private string _USU_EMAIL;
		
		private string _USU_SENHA;
		
		private string _USU_FOTO_PERFIL;
		
		private string _USU_USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSU_IDChanging(int value);
    partial void OnUSU_IDChanged();
    partial void OnUSU_NOMEChanging(string value);
    partial void OnUSU_NOMEChanged();
    partial void OnUSU_SOBRENOMEChanging(string value);
    partial void OnUSU_SOBRENOMEChanged();
    partial void OnUSU_EMAILChanging(string value);
    partial void OnUSU_EMAILChanged();
    partial void OnUSU_SENHAChanging(string value);
    partial void OnUSU_SENHAChanged();
    partial void OnUSU_FOTO_PERFILChanging(string value);
    partial void OnUSU_FOTO_PERFILChanged();
    partial void OnUSU_USUARIOChanging(string value);
    partial void OnUSU_USUARIOChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int USU_ID
		{
			get
			{
				return this._USU_ID;
			}
			set
			{
				if ((this._USU_ID != value))
				{
					this.OnUSU_IDChanging(value);
					this.SendPropertyChanging();
					this._USU_ID = value;
					this.SendPropertyChanged("USU_ID");
					this.OnUSU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_NOME", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string USU_NOME
		{
			get
			{
				return this._USU_NOME;
			}
			set
			{
				if ((this._USU_NOME != value))
				{
					this.OnUSU_NOMEChanging(value);
					this.SendPropertyChanging();
					this._USU_NOME = value;
					this.SendPropertyChanged("USU_NOME");
					this.OnUSU_NOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_SOBRENOME", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string USU_SOBRENOME
		{
			get
			{
				return this._USU_SOBRENOME;
			}
			set
			{
				if ((this._USU_SOBRENOME != value))
				{
					this.OnUSU_SOBRENOMEChanging(value);
					this.SendPropertyChanging();
					this._USU_SOBRENOME = value;
					this.SendPropertyChanged("USU_SOBRENOME");
					this.OnUSU_SOBRENOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_EMAIL", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string USU_EMAIL
		{
			get
			{
				return this._USU_EMAIL;
			}
			set
			{
				if ((this._USU_EMAIL != value))
				{
					this.OnUSU_EMAILChanging(value);
					this.SendPropertyChanging();
					this._USU_EMAIL = value;
					this.SendPropertyChanged("USU_EMAIL");
					this.OnUSU_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_SENHA", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string USU_SENHA
		{
			get
			{
				return this._USU_SENHA;
			}
			set
			{
				if ((this._USU_SENHA != value))
				{
					this.OnUSU_SENHAChanging(value);
					this.SendPropertyChanging();
					this._USU_SENHA = value;
					this.SendPropertyChanged("USU_SENHA");
					this.OnUSU_SENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_FOTO_PERFIL", DbType="VarChar(MAX)")]
		public string USU_FOTO_PERFIL
		{
			get
			{
				return this._USU_FOTO_PERFIL;
			}
			set
			{
				if ((this._USU_FOTO_PERFIL != value))
				{
					this.OnUSU_FOTO_PERFILChanging(value);
					this.SendPropertyChanging();
					this._USU_FOTO_PERFIL = value;
					this.SendPropertyChanged("USU_FOTO_PERFIL");
					this.OnUSU_FOTO_PERFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_USUARIO", DbType="VarChar(50)")]
		public string USU_USUARIO
		{
			get
			{
				return this._USU_USUARIO;
			}
			set
			{
				if ((this._USU_USUARIO != value))
				{
					this.OnUSU_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._USU_USUARIO = value;
					this.SendPropertyChanged("USU_USUARIO");
					this.OnUSU_USUARIOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
